services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: showtime_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
