syntax = "proto3";

package esp_status;

message DmxConfig {
  uint32 universe = 1;
  uint32 start_addr = 2;
  uint32 led_count = 3;
  uint32 esp_pin = 4;
  uint32 mode = 5;
}

message EspStatusMessage {
  uint32 r = 1;
  uint32 g = 2;
  uint32 b = 3;
  uint32 last_sacn_pkt = 4;
  string device_name = 5;
  uint32 signal_strength = 6;
  string mac_addr = 7;
  repeated DmxConfig dmx_config = 8;
}

message UpdateConfig {
  string mac_addr = 1;
  string device_name = 2;
  repeated DmxConfig dmx_config = 3;
  bool is_ack = 4;
}

message SetDmx {
  message OutputData {
    uint32 esp_pin = 1;
    bytes dmx_values = 2;
  }
  repeated OutputData outputs = 1;
}
