/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(esp_status_DmxConfig, esp_status_DmxConfig, AUTO)


PB_BIND(esp_status_EspStatusMessage, esp_status_EspStatusMessage, 2)


PB_BIND(esp_status_UpdateConfig, esp_status_UpdateConfig, 2)


PB_BIND(esp_status_SetDmx, esp_status_SetDmx, 4)


PB_BIND(esp_status_SetDmx_OutputData, esp_status_SetDmx_OutputData, AUTO)



