/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_ESP_STATUS_MESSAGES_PB_H_INCLUDED
#define PB_ESP_STATUS_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _esp_status_DmxConfig {
    uint8_t universe;
    uint16_t start_addr;
    uint16_t led_count;
    uint32_t esp_pin;
    uint32_t mode;
} esp_status_DmxConfig;

typedef struct _esp_status_EspStatusMessage {
    uint32_t r;
    uint32_t g;
    uint32_t b;
    uint32_t last_sacn_pkt;
    char device_name[64];
    uint32_t signal_strength;
    char mac_addr[32];
    pb_size_t dmx_config_count;
    esp_status_DmxConfig dmx_config[8];
} esp_status_EspStatusMessage;

typedef struct _esp_status_UpdateConfig {
    char mac_addr[32];
    char device_name[64];
    pb_size_t dmx_config_count;
    esp_status_DmxConfig dmx_config[8];
    bool is_ack;
} esp_status_UpdateConfig;

typedef PB_BYTES_ARRAY_T(512) esp_status_SetDmx_OutputData_dmx_values_t;
typedef struct _esp_status_SetDmx_OutputData {
    uint32_t dmx_start_addr;
    esp_status_SetDmx_OutputData_dmx_values_t dmx_values;
} esp_status_SetDmx_OutputData;

typedef struct _esp_status_SetDmx {
    pb_size_t outputs_count;
    esp_status_SetDmx_OutputData outputs[8];
} esp_status_SetDmx;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define esp_status_DmxConfig_init_default        {0, 0, 0, 0, 0}
#define esp_status_EspStatusMessage_init_default {0, 0, 0, 0, "", 0, "", 0, {esp_status_DmxConfig_init_default, esp_status_DmxConfig_init_default, esp_status_DmxConfig_init_default, esp_status_DmxConfig_init_default, esp_status_DmxConfig_init_default, esp_status_DmxConfig_init_default, esp_status_DmxConfig_init_default, esp_status_DmxConfig_init_default}}
#define esp_status_UpdateConfig_init_default     {"", "", 0, {esp_status_DmxConfig_init_default, esp_status_DmxConfig_init_default, esp_status_DmxConfig_init_default, esp_status_DmxConfig_init_default, esp_status_DmxConfig_init_default, esp_status_DmxConfig_init_default, esp_status_DmxConfig_init_default, esp_status_DmxConfig_init_default}, 0}
#define esp_status_SetDmx_init_default           {0, {esp_status_SetDmx_OutputData_init_default, esp_status_SetDmx_OutputData_init_default, esp_status_SetDmx_OutputData_init_default, esp_status_SetDmx_OutputData_init_default, esp_status_SetDmx_OutputData_init_default, esp_status_SetDmx_OutputData_init_default, esp_status_SetDmx_OutputData_init_default, esp_status_SetDmx_OutputData_init_default}}
#define esp_status_SetDmx_OutputData_init_default {0, {0, {0}}}
#define esp_status_DmxConfig_init_zero           {0, 0, 0, 0, 0}
#define esp_status_EspStatusMessage_init_zero    {0, 0, 0, 0, "", 0, "", 0, {esp_status_DmxConfig_init_zero, esp_status_DmxConfig_init_zero, esp_status_DmxConfig_init_zero, esp_status_DmxConfig_init_zero, esp_status_DmxConfig_init_zero, esp_status_DmxConfig_init_zero, esp_status_DmxConfig_init_zero, esp_status_DmxConfig_init_zero}}
#define esp_status_UpdateConfig_init_zero        {"", "", 0, {esp_status_DmxConfig_init_zero, esp_status_DmxConfig_init_zero, esp_status_DmxConfig_init_zero, esp_status_DmxConfig_init_zero, esp_status_DmxConfig_init_zero, esp_status_DmxConfig_init_zero, esp_status_DmxConfig_init_zero, esp_status_DmxConfig_init_zero}, 0}
#define esp_status_SetDmx_init_zero              {0, {esp_status_SetDmx_OutputData_init_zero, esp_status_SetDmx_OutputData_init_zero, esp_status_SetDmx_OutputData_init_zero, esp_status_SetDmx_OutputData_init_zero, esp_status_SetDmx_OutputData_init_zero, esp_status_SetDmx_OutputData_init_zero, esp_status_SetDmx_OutputData_init_zero, esp_status_SetDmx_OutputData_init_zero}}
#define esp_status_SetDmx_OutputData_init_zero   {0, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define esp_status_DmxConfig_universe_tag        1
#define esp_status_DmxConfig_start_addr_tag      2
#define esp_status_DmxConfig_led_count_tag       3
#define esp_status_DmxConfig_esp_pin_tag         4
#define esp_status_DmxConfig_mode_tag            5
#define esp_status_EspStatusMessage_r_tag        1
#define esp_status_EspStatusMessage_g_tag        2
#define esp_status_EspStatusMessage_b_tag        3
#define esp_status_EspStatusMessage_last_sacn_pkt_tag 4
#define esp_status_EspStatusMessage_device_name_tag 5
#define esp_status_EspStatusMessage_signal_strength_tag 6
#define esp_status_EspStatusMessage_mac_addr_tag 7
#define esp_status_EspStatusMessage_dmx_config_tag 8
#define esp_status_UpdateConfig_mac_addr_tag     1
#define esp_status_UpdateConfig_device_name_tag  2
#define esp_status_UpdateConfig_dmx_config_tag   3
#define esp_status_UpdateConfig_is_ack_tag       4
#define esp_status_SetDmx_OutputData_dmx_start_addr_tag 1
#define esp_status_SetDmx_OutputData_dmx_values_tag 2
#define esp_status_SetDmx_outputs_tag            1

/* Struct field encoding specification for nanopb */
#define esp_status_DmxConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   universe,          1) \
X(a, STATIC,   SINGULAR, UINT32,   start_addr,        2) \
X(a, STATIC,   SINGULAR, UINT32,   led_count,         3) \
X(a, STATIC,   SINGULAR, UINT32,   esp_pin,           4) \
X(a, STATIC,   SINGULAR, UINT32,   mode,              5)
#define esp_status_DmxConfig_CALLBACK NULL
#define esp_status_DmxConfig_DEFAULT NULL

#define esp_status_EspStatusMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   r,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   g,                 2) \
X(a, STATIC,   SINGULAR, UINT32,   b,                 3) \
X(a, STATIC,   SINGULAR, UINT32,   last_sacn_pkt,     4) \
X(a, STATIC,   SINGULAR, STRING,   device_name,       5) \
X(a, STATIC,   SINGULAR, UINT32,   signal_strength,   6) \
X(a, STATIC,   SINGULAR, STRING,   mac_addr,          7) \
X(a, STATIC,   REPEATED, MESSAGE,  dmx_config,        8)
#define esp_status_EspStatusMessage_CALLBACK NULL
#define esp_status_EspStatusMessage_DEFAULT NULL
#define esp_status_EspStatusMessage_dmx_config_MSGTYPE esp_status_DmxConfig

#define esp_status_UpdateConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   mac_addr,          1) \
X(a, STATIC,   SINGULAR, STRING,   device_name,       2) \
X(a, STATIC,   REPEATED, MESSAGE,  dmx_config,        3) \
X(a, STATIC,   SINGULAR, BOOL,     is_ack,            4)
#define esp_status_UpdateConfig_CALLBACK NULL
#define esp_status_UpdateConfig_DEFAULT NULL
#define esp_status_UpdateConfig_dmx_config_MSGTYPE esp_status_DmxConfig

#define esp_status_SetDmx_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  outputs,           1)
#define esp_status_SetDmx_CALLBACK NULL
#define esp_status_SetDmx_DEFAULT NULL
#define esp_status_SetDmx_outputs_MSGTYPE esp_status_SetDmx_OutputData

#define esp_status_SetDmx_OutputData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dmx_start_addr,    1) \
X(a, STATIC,   SINGULAR, BYTES,    dmx_values,        2)
#define esp_status_SetDmx_OutputData_CALLBACK NULL
#define esp_status_SetDmx_OutputData_DEFAULT NULL

extern const pb_msgdesc_t esp_status_DmxConfig_msg;
extern const pb_msgdesc_t esp_status_EspStatusMessage_msg;
extern const pb_msgdesc_t esp_status_UpdateConfig_msg;
extern const pb_msgdesc_t esp_status_SetDmx_msg;
extern const pb_msgdesc_t esp_status_SetDmx_OutputData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define esp_status_DmxConfig_fields &esp_status_DmxConfig_msg
#define esp_status_EspStatusMessage_fields &esp_status_EspStatusMessage_msg
#define esp_status_UpdateConfig_fields &esp_status_UpdateConfig_msg
#define esp_status_SetDmx_fields &esp_status_SetDmx_msg
#define esp_status_SetDmx_OutputData_fields &esp_status_SetDmx_OutputData_msg

/* Maximum encoded size of messages (where known) */
#define ESP_STATUS_MESSAGES_PB_H_MAX_SIZE        esp_status_SetDmx_size
#define esp_status_DmxConfig_size                23
#define esp_status_EspStatusMessage_size         328
#define esp_status_SetDmx_OutputData_size        521
#define esp_status_SetDmx_size                   4192
#define esp_status_UpdateConfig_size             300

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
