name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Build
        run: cd client && cargo build --release
      - name: Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            client/target/release/showtime.exe
            client/target/release/showtime
